// La pantalla del móvil en Chromium (390×844) con el motor simulado: pestañas, preguntas, 6 cifras, emparejar
const path = require('path')
const { chromium } = require('../../node_modules/playwright-core')
const out = process.argv[2] || '/tmp/ui'
;(async () => {
  const exe = process.env.CHROMIUM || (require('fs').existsSync('/opt/pw-browsers/chromium') ? '/opt/pw-browsers/chromium' : undefined)
  const b = await chromium.launch(exe ? { executablePath: exe } : {})
  const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 })
  const errs = []; p.on('pageerror', (e) => errs.push(e.message)); p.on('console', (m) => (m.type() === 'error' || /Content Security Policy|Refused/.test(m.text())) && errs.push(m.text()))
  await p.addInitScript({ path: path.join(__dirname, 'ui-mock.js') })
  await p.goto('file://' + path.join(__dirname, '../assets/ui/index.html'))
  await p.waitForTimeout(1200)
  // en este servidor el WebGL de Nubo va a 3 fps (sin gráfica): se pulsa por JS para no esperar a la animación
  const tap = (sel) => p.$eval(sel, (el) => el.click())
  const shot = (o) => p.screenshot({ ...o, timeout: 60000, animations: 'disabled', caret: 'initial' }).catch((e) => console.log('(sin captura: ' + e.message.split('\n')[0] + ')'))
  const ok = (c, m) => { console.log((c ? '✓ ' : '✗ ') + m); if (!c) process.exitCode = 1 }
  ok(await p.locator('.peer-name').first().textContent() === 'PC-ESTUDIO', 'Enviar: tarjeta del PC')
  ok(await p.locator('.prog').count() === 1, 'Enviar: progreso del envío')
  await shot({ path: out + '/1-enviar.png' })
  await tap('[data-pick="media"]')
  ok((await p.evaluate(() => window.__calls)).some((c) => c[0] === 'pick' && c[1] === 'media'), 'Fotos abre el selector')
  await tap('[data-tab="recibido"]'); await p.waitForTimeout(200)
  await shot({ path: out + '/2-recibido.png' })
  await p.evaluate(() => window.puente.ev('ask', { id: 'a1', name: 'PC-ESTUDIO', files: 2, size: 3e6, private: true, via: 'relé', list: [{ rel: 'Fotos/playa.jpg', size: 2e6 }, { rel: 'nota.txt', size: 1e6 }] }))
  await p.waitForTimeout(300)
  ok(await p.locator('.modal h2').textContent() === 'PC-ESTUDIO quiere enviarte 2 archivos', 'pregunta al recibir')
  await shot({ path: out + '/3-pregunta.png' })
  await tap('#si')
  ok((await p.evaluate(() => window.__calls)).some((c) => c[0] === 'answer' && c[1] === 'a1' && c[2] === true), 'Aceptar llega al motor')
  await tap('[data-tab="emparejar"]'); await p.waitForTimeout(300)
  await tap('[data-lan="192.168.1.20"]'); await p.waitForTimeout(100)
  await p.$eval('#code', (el) => { el.focus(); el.value = 'k7qm4r2x'; el.dispatchEvent(new Event('input')) })
  ok(await p.inputValue('#code') === 'K7QM-4R2X', 'código con guion automático')
  ok(await p.locator('.lan-pc.on[data-lan="192.168.1.20"]').count() === 1 && await p.locator('#host').count() === 0, 'tocar el PC lo elige (sin escribir direcciones)')
  await shot({ path: out + '/4-emparejar.png' })
  await tap('#pairGo')
  const pw = (await p.evaluate(() => window.__calls)).find((c) => c[0] === 'pairWith')
  ok(pw && pw[1] === '192.168.1.20' && pw[2] === 47830 && pw[3] === 'K7QM4R2X', 'Emparejar llama al motor')
  await p.evaluate(() => window.puente.ev('pair-confirm', { id: 'p1', sas: '398299', name: 'PC-SALON', fp: 'QWER-TYUP-ASDF' }))
  await p.waitForTimeout(200)
  ok((await p.locator('.sas').textContent()).replace(/\s/g, '') === '398299', '6 cifras en pantalla')
  await shot({ path: out + '/5-cifras.png' })
  await tap('#si')
  await p.evaluate(() => window.puente.ev('pair-ended', { id: 'p1', ok: true, name: 'PC-SALON' }))
  await p.waitForTimeout(300)
  ok(await p.locator('.tabs button.on').getAttribute('data-tab') === 'enviar', 'al emparejar vuelve a Enviar')
  await tap('[data-tab="emparejar"]'); await tap('#pairShow'); await p.waitForTimeout(200)
  ok(await p.locator('.big-code').textContent() === 'K7QM-4R2X', 'Mostrar código del móvil')
  await tap('[data-tab="ajustes"]'); await p.waitForTimeout(200)
  await shot({ path: out + '/6-ajustes.png', fullPage: true })
  await tap('#privBtn'); await p.waitForTimeout(100)
  ok(await p.locator('#privBtn.on').count() === 1, 'sesión privada se enciende')
  await p.evaluate(() => window.puente.ev('shared', { count: 3 }))
  await p.waitForTimeout(300)
  await tap('#nuboPet'); await p.waitForTimeout(200)
  ok(await p.locator('.help li').count() > 5, 'Nubo abre la ayuda')
  await shot({ path: out + '/7-nubo.png' })
  ok(await p.evaluate(() => window.puente.back()) === true, 'atrás cierra la ventana')
  await p.$eval('#panicBtn', (el) => { el.click(); el.click() })
  const pc = await p.evaluate(() => [window.__calls.map((c) => c[0]).slice(-6), document.querySelector('#modal').innerHTML.slice(0, 80), document.querySelector('#toast').textContent])
  ok(pc[0].includes('panic'), 'pánico con dos toques ' + JSON.stringify(pc))
  // borrar lo enviado: ajuste y pregunta
  await tap('[data-tab="ajustes"]'); await p.waitForTimeout(200)
  await tap('[data-del="preguntar"]'); await p.waitForTimeout(200)
  ok((await p.evaluate(() => window.__calls)).some((c) => c[0] === 'settings' && c[1].deleteAfter === 'preguntar'), 'Ajustes: «Después de enviar → Preguntar»')
  ok(await p.locator('[data-del="preguntar"].on').count() === 1, 'la opción elegida queda marcada')
  await shot({ path: out + '/8-borrar-ajuste.png', fullPage: true })
  await p.evaluate(() => window.puente.ev('sent-ask-delete', { id: 'abcdef0123456789', name: 'PC-ESTUDIO', files: 12, size: 48e6 }))
  await p.waitForTimeout(300)
  ok((await p.locator('.modal h2').textContent()).includes('Ya está en PC-ESTUDIO'), 'tras enviar: «¿Lo borro del móvil?»')
  await shot({ path: out + '/9-borrar-pregunta.png' })
  await tap('#si')
  ok((await p.evaluate(() => window.__calls)).some((c) => c[0] === 'deleteSent' && c[1] === 'abcdef0123456789' && c[2] === true), 'Borrar del móvil llega al motor')
  await p.evaluate(() => window.puente.ev('deleted', { deleted: 10, failed: 0, consent: 2 }))
  await p.waitForTimeout(300)
  ok((await p.locator('.modal h2').textContent()) === 'Falta tu permiso', 'si Android pide permiso, se explica antes')
  await tap('#si')
  ok((await p.evaluate(() => window.__calls)).some((c) => c[0] === 'deleteConsent'), 'y abre la ventana del sistema')
  // enlace del QR: rellena, pero NO empareja solo
  const before = (await p.evaluate(() => window.__calls)).filter((c) => c[0] === 'pairWith').length
  await p.evaluate(() => window.puente.ev('deeplink', { hosts: ['192.168.1.20', '10.0.0.5'], port: 47830, code: 'NYB9-88EK', name: 'PC-SALON' }))
  await p.waitForTimeout(400)
  ok((await p.evaluate(() => window.__calls)).filter((c) => c[0] === 'pairWith').length === before, 'el QR no empareja solo')
  ok(await p.inputValue('#code') === 'NYB9-88EK' && (await p.locator('.banner').textContent()).includes('PC-SALON'), 'el QR rellena el código y avisa con quién')
  await tap('#pairGo')
  const pw2 = (await p.evaluate(() => window.__calls)).filter((c) => c[0] === 'pairWith').pop()
  ok(pw2 && pw2[1] === '192.168.1.20,10.0.0.5' && pw2[3] === 'NYB988EK', 'al tocar «Emparejar» prueba las direcciones del QR')
  // sin el motor de la mascota (no va en el repositorio público), su archivo falta: ese aviso no cuenta
  const sinMascota = !require('fs').existsSync(path.join(__dirname, '../assets/ui/fluffy-friends.js'))
  const reales = errs.filter((e) => !(sinMascota && /ERR_FILE_NOT_FOUND/.test(e)))
  ok(!reales.length, 'sin errores en la consola (ni de CSP) ' + reales.join(' | '))
  await b.close()
})()
